import { defineField, defineType, type StringRule } from 'sanity'

const tokenHelp =
  'Tokeny: {bookingId} = numer zlecenia, {name} = pełne imię. W innych szablonach: {firstName}, {projectTypeGenitive}, {titleDate}, {meetingDateLabel}, {meetingTime}, {slotMinutes}, {email}, {phone}, {message}, {source} — w zależności od typu maila (patrz opis pola).'

const headerEmojiHelp =
  'Duża emotka nad głównym nagłówkiem. Wklej np. 📧 lub zostaw puste — wtedy nie renderujemy żadnej (tylko tekst lub sam logo w mailu kontaktowym).'

const colorFieldHelp =
  'Kolor w CSS: #RRGGBB (np. #ffffff) lub rgba(...). Treść maila to HTML z inline style — unikaj nazw kolorów („white”).'

function isValidEmailCssColor(value: unknown): boolean {
  if (typeof value !== 'string') return false
  const s = value.trim()
  if (/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(s)) return true
  if (/^rgba?\(\s*[0-9.\s,%]+\s*\)$/i.test(s)) return true
  return false
}

const colorValidation = (Rule: StringRule) =>
  Rule.custom((value) => {
    if (value === undefined || value === '') return 'Wymagane'
    return isValidEmailCssColor(value) ? true : 'Podaj #RGB / #RRGGBB lub rgba(...)'
  })

/** Kolor obok treści — szablon HTML używa inline style. */
function ec(name: string, title: string, initialValue: string) {
  return defineField({
    name,
    title,
    type: 'string',
    description: colorFieldHelp,
    initialValue,
    validation: colorValidation,
  })
}

export default defineType({
  name: 'emailTemplates',
  title: '📧 Treści emaili',
  type: 'document',
  groups: [
    { name: 'quote', title: 'Konfigurator wyceny', default: true },
    { name: 'contact', title: 'Formularz kontaktowy' },
    { name: 'meeting', title: 'Rezerwacja rozmowy' },
    { name: 'pipeline', title: 'Zlecenie (umowa · przelew · start · koniec · odrzucenie)' },
  ],
  fields: [
    defineField({
      name: 'quoteRequestClient',
      title: '📨 Klient — zapytanie z konfiguratora (pierwszy kontakt)',
      group: 'quote',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          description: 'Tokeny: {projectTypeGenitive}, {titleDate} (data DD.MM.RRRR), ew. {name}, {bookingId}.',
          type: 'string',
          initialValue: 'Syntance - Zapytanie o wycenę {projectTypeGenitive} - {titleDate}',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'headerEmoji',
          title: '😀 Emotka nad tytułem',
          description: headerEmojiHelp,
          type: 'string',
          initialValue: '📨',
          validation: (Rule) => Rule.max(32),
        }),
        ec('mailBackgroundColor', 'Tło karty maila (600px)', '#111111'),
        ec('sectionPanelBackgroundColor', 'Tło bloku podsumowania listy / tabeli', '#1a1a1a'),
        defineField({
          name: 'heading',
          title: 'Nagłówek (h1)',
          type: 'string',
          initialValue: 'Zapytanie o wycenę przyjęte',
          validation: (Rule) => Rule.required(),
        }),
        ec('headingColor', 'Kolor — nagłówek h1', '#ffffff'),
        defineField({
          name: 'greetingTemplate',
          title: 'Powitanie',
          description: 'Np. Cześć {name}, — imię z konfiguratora.',
          type: 'string',
          initialValue: 'Cześć {name},',
        }),
        ec('greetingColor', 'Kolor — powitanie i akapit pod spodem', '#cccccc'),
        defineField({
          name: 'intro',
          title: 'Wstęp',
          type: 'text',
          rows: 4,
          initialValue:
            'Dziękujemy za zainteresowanie współpracą z Syntance! Otrzymaliśmy Twoje zapytanie i odezwiemy się w ciągu 24 godzin, żeby ustalić termin realizacji.',
        }),
        ec('introColor', 'Kolor — wstęp', '#cccccc'),
        defineField({
          name: 'nextStepsTitle',
          title: 'Tytuł ramki „co dalej”',
          type: 'string',
          initialValue: 'Co dalej?',
        }),
        ec('nextStepsTitleColor', 'Kolor — tytuł ramki „co dalej”', '#22c55e'),
        defineField({
          name: 'nextStepsBody',
          title: 'Treść ramki „co dalej”',
          type: 'text',
          rows: 3,
          initialValue:
            'Skontaktujemy się z Tobą, żeby omówić szczegóły, ustalić termin realizacji i przejść do akceptacji wyceny.',
        }),
        ec('nextStepsBodyColor', 'Kolor — treść ramki „co dalej”', '#86efac'),
        defineField({
          name: 'footerNote',
          title: 'Stopka treści',
          type: 'text',
          rows: 2,
          initialValue:
            'Jeśli masz pytania, odpowiedz na ten email lub napisz na kontakt@syntance.com.',
        }),
        ec('footerNoteColor', 'Kolor — stopka treści', '#888888'),
        ec('referenceLineMutedColor', 'Kolor — etykieta „Nr referencyjny:” (tekst przed numerem)', '#9e9e9e'),
        ec('referenceLineAccentColor', 'Kolor — numer referencyjny (h1 pod spodem)', '#a29bfe'),
        ec('summarySectionHeadingColor', 'Kolor — nagłówek „Podsumowanie zlecenia” (h3)', '#ffffff'),
        ec('tableLabelColor', 'Kolor — etykiety w tabeli podsumowania', '#888888'),
        ec('tableValueColor', 'Kolor — wartości w tabeli', '#ffffff'),
        ec('tableAccentColor', 'Kolor — akcenty w tabeli (zaliczka itp.)', '#a78bfa'),
        ec('itemListTextColor', 'Kolor — lista pozycji koszyka', '#cccccc'),
        ec('listBulletColor', 'Kolor — kropki listy', '#a78bfa'),
        ec('calloutBackgroundColor', 'Tło ramki wyróżnienia (rgba)', 'rgba(34,197,94,0.08)'),
        ec('calloutBorderColor', 'Obramowanie ramki wyróżnienia', 'rgba(34,197,94,0.19)'),
      ],
    }),
    defineField({
      name: 'quoteRequestOwner',
      title: '🔔 Zespół — nowe zapytanie z konfiguratora',
      group: 'quote',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          description: 'Jak u klienta: {projectTypeGenitive}, {titleDate}.',
          type: 'string',
          initialValue: 'Syntance - Zapytanie o wycenę {projectTypeGenitive} - {titleDate}',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'headerEmoji',
          title: '😀 Emotka nad tytułem',
          description: headerEmojiHelp,
          type: 'string',
          initialValue: '🔔',
          validation: (Rule) => Rule.max(32),
        }),
        ec('mailBackgroundColor', 'Tło karty maila (600px)', '#111111'),
        ec('sectionPanelBackgroundColor', 'Tło bloków sekcji (dane, wycena, lista)', '#1a1a1a'),
        defineField({
          name: 'headerTitle',
          title: 'Nagłówek maila',
          type: 'string',
          initialValue: 'Nowe zapytanie o wycenę',
        }),
        ec('headerTitleColor', 'Kolor — nagłówek h1', '#ffffff'),
        ec('referenceLineMutedColor', 'Kolor — przedrostek „ID:” w nagłówku', '#9e9e9e'),
        ec('referenceLineAccentColor', 'Kolor — numer zapytania w nagłówku', '#a29bfe'),
        ec('headerMetaColor', 'Kolor — data po „•” w nagłówku', '#888888'),
        ec('sectionHeadingColor', 'Kolor — nagłówki sekcji (Dane klienta, Wycena…)', '#ffffff'),
        ec('clientFieldLabelColor', 'Kolor — etykiety pól klienta', '#888888'),
        ec('clientFieldValueColor', 'Kolor — wartości pól klienta', '#ffffff'),
        ec('descriptionTextColor', 'Kolor — opis / treść w szarych blokach', '#cccccc'),
        ec('linkAccentColor', 'Kolor — linki (email, www)', '#a78bfa'),
        ec('pricingLabelColor', 'Kolor — etykiety w tabeli wyceny', '#888888'),
        ec('pricingValueNettoColor', 'Kolor — kwota netto', '#ffffff'),
        ec('pricingValueBruttoColor', 'Kolor — kwota brutto', '#aaaaaa'),
        ec('pricingDepositColor', 'Kolor — zaliczka', '#a78bfa'),
        ec('pricingTimeColor', 'Kolor — czas realizacji', '#ffffff'),
        ec('dividerRowColor', 'Kolor — linie między wierszami wyceny', '#333333'),
        ec('itemsListTextColor', 'Kolor — lista wybranych elementów', '#cccccc'),
        ec('listBulletColor', 'Kolor — kropki listy elementów', '#a78bfa'),
        ec('actionStripBackgroundColor', 'Tło paska z przyciskami', '#0d0d0d'),
        defineField({
          name: 'actionPrompt',
          title: 'Tekst nad przyciskami Akceptuj / Odrzuć',
          type: 'string',
          initialValue: 'Kliknij aby zaakceptować lub odrzucić zlecenie:',
        }),
        ec('actionPromptColor', 'Kolor — tekst nad przyciskami', '#888888'),
        defineField({
          name: 'acceptButtonLabel',
          title: 'Etykieta przycisku akceptacji',
          type: 'string',
          initialValue: '✓ Akceptuj zlecenie',
        }),
        ec('acceptButtonGradientStartColor', 'Przycisk akceptacji — gradient (początek)', '#22c55e'),
        ec('acceptButtonGradientEndColor', 'Przycisk akceptacji — gradient (koniec)', '#16a34a'),
        ec('acceptButtonTextColor', 'Przycisk akceptacji — kolor tekstu', '#ffffff'),
        defineField({
          name: 'rejectButtonLabel',
          title: 'Etykieta przycisku odrzucenia',
          type: 'string',
          initialValue: '✗ Odrzuć',
        }),
        ec('rejectButtonBackgroundColor', 'Przycisk odrzucenia — tło', '#333333'),
        ec('rejectButtonTextColor', 'Przycisk odrzucenia — tekst', '#ffffff'),
        defineField({
          name: 'autoFooterNote',
          title: 'Stopka (automatyczny mail)',
          type: 'text',
          rows: 2,
          initialValue: 'Ten email został wygenerowany automatycznie przez konfigurator Syntance.',
        }),
        ec('autoFooterNoteColor', 'Kolor — automatyczna stopka', '#555555'),
      ],
    }),
    defineField({
      name: 'contactFormClient',
      title: '✉️ Klient — potwierdzenie formularza kontaktowego',
      group: 'contact',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          type: 'string',
          initialValue: 'Otrzymaliśmy Twoje zapytanie — Syntance',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'headerEmoji',
          title: '😀 Emotka nad tytułem (nad logo)',
          description: headerEmojiHelp,
          type: 'string',
          initialValue: '',
          validation: (Rule) => Rule.max(32),
        }),
        ec('mailBackgroundColor', 'Tło karty maila', '#111111'),
        ec('headerBandBackgroundColor', 'Tło pasma z logo i h1', '#1a1a1a'),
        defineField({
          name: 'heading',
          title: 'Nagłówek (h1)',
          type: 'string',
          initialValue: 'Dziękujemy za wiadomość!',
        }),
        ec('headingColor', 'Kolor — nagłówek h1', '#ffffff'),
        defineField({
          name: 'greetingTemplate',
          title: 'Powitanie',
          description: '{firstName} — pierwsze słowo z imienia i nazwiska.',
          type: 'string',
          initialValue: 'Cześć {firstName},',
        }),
        ec('greetingColor', 'Kolor — linia powitania (tekst obok imienia)', '#cccccc'),
        defineField({
          name: 'bodyParagraph1',
          title: 'Akapit 1',
          type: 'text',
          rows: 2,
          initialValue: 'Otrzymaliśmy Twoje zapytanie i już je analizujemy.',
        }),
        ec('bodyParagraph1Color', 'Kolor — akapit 1', '#cccccc'),
        defineField({
          name: 'bodyParagraph2',
          title: 'Akapit 2',
          type: 'text',
          rows: 2,
          initialValue: 'Odezwiemy się w ciągu 24 godzin w dni robocze.',
        }),
        ec('bodyParagraph2Color', 'Kolor — akapit 2', '#cccccc'),
        defineField({
          name: 'asideTitle',
          title: 'Tytuł sekcji linków',
          type: 'string',
          initialValue: 'W międzyczasie możesz:',
        }),
        ec('asideTitleColor', 'Kolor — tytuł sekcji linków', '#888888'),
        defineField({
          name: 'link1Label',
          title: 'Link 1 — tekst',
          type: 'string',
          initialValue: '📋 Sprawdzić nasz cennik i ofertę',
        }),
        ec('link1LabelColor', 'Kolor — tekst linku 1', '#a78bfa'),
        ec('link1RowBackgroundColor', 'Tło wiersza linku 1', 'rgba(34,197,94,0.08)'),
        ec('link1RowBorderColor', 'Obramowanie wiersza linku 1', 'rgba(34,197,94,0.19)'),
        defineField({
          name: 'link1Url',
          title: 'Link 1 — URL',
          type: 'string',
          initialValue: 'https://syntance.com/cennik',
        }),
        defineField({
          name: 'link2Label',
          title: 'Link 2 — tekst',
          type: 'string',
          initialValue: '🎯 Dowiedzieć się więcej o naszej strategii',
        }),
        ec('link2LabelColor', 'Kolor — tekst linku 2', '#93c5fd'),
        ec('link2RowBackgroundColor', 'Tło wiersza linku 2', '#1a1a1a'),
        ec('link2RowBorderColor', 'Obramowanie wiersza linku 2', '#222222'),
        defineField({
          name: 'link2Url',
          title: 'Link 2 — URL',
          type: 'string',
          initialValue: 'https://syntance.com/strategia-marketingu-i-sprzedazy',
        }),
        defineField({
          name: 'closingLine',
          title: 'Zakończenie',
          type: 'string',
          initialValue: 'Do usłyszenia!',
        }),
        ec('closingLineColor', 'Kolor — zakończenie', '#cccccc'),
        ec('footerBandBackgroundColor', 'Tło pasma stopki w karcie', '#0d0d0d'),
        defineField({
          name: 'footerTagline',
          title: 'Stopka — tagline',
          type: 'string',
          initialValue: 'Syntance — Strony i sklepy, które działają.',
        }),
        ec('footerTaglineColor', 'Kolor — tagline (pogrubienie)', '#888888'),
        ec('footerSecondaryLinkColor', 'Kolor — linki strony i email w stopce', '#666666'),
        defineField({
          name: 'footerSiteLabel',
          title: 'Stopka — etykieta strony',
          type: 'string',
          initialValue: 'syntance.com',
        }),
        defineField({
          name: 'footerSiteUrl',
          title: 'Stopka — URL strony',
          type: 'string',
          initialValue: 'https://syntance.com',
        }),
        defineField({
          name: 'footerEmail',
          title: 'Stopka — email',
          type: 'string',
          initialValue: 'biuro@syntance.com',
        }),
        defineField({
          name: 'legalNote',
          title: 'Nota prawna pod stopką',
          type: 'text',
          rows: 2,
          initialValue:
            'Ten email został wysłany automatycznie w odpowiedzi na Twoje zapytanie przez formularz kontaktowy na stronie syntance.com.',
        }),
        ec('legalNoteColor', 'Kolor — nota prawna (pod kartą)', '#555555'),
      ],
    }),
    defineField({
      name: 'contactFormOwner',
      title: '📥 Zespół — lead z formularza (plaintext)',
      group: 'contact',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          description: '{name} — imię i nazwisko',
          type: 'string',
          initialValue: 'Nowy lead ze strony: {name}',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'bodyTemplate',
          title: 'Treść (plaintext)',
          description: 'Tokeny: {name}, {email}, {phone}, {source}, {message}',
          type: 'text',
          rows: 8,
          initialValue: `Imię i nazwisko: {name}
Email: {email}
Telefon: {phone}
Źródło: {source}

Wiadomość:
{message}`,
        }),
      ],
    }),
    defineField({
      name: 'meetingBookingClient',
      title: '📅 Klient — potwierdzenie rezerwacji rozmowy',
      group: 'meeting',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          description: '{meetingDateLabel}, {meetingTime} — np. poniedziałek 12 maja 2025, 14:00.',
          type: 'string',
          initialValue: 'Potwierdzenie rozmowy — {meetingDateLabel}, {meetingTime}',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'headerEmoji',
          title: '😀 Emotka nad tytułem',
          description: headerEmojiHelp,
          type: 'string',
          initialValue: '📅',
          validation: (Rule) => Rule.max(32),
        }),
        ec('mailBackgroundColor', 'Tło karty maila', '#111111'),
        ec('sectionPanelBackgroundColor', 'Tło nagłówka (pas z h1)', '#1a1a1a'),
        defineField({
          name: 'headingTemplate',
          title: 'Nagłówek',
          description: '{name} — pełne imię',
          type: 'string',
          initialValue: 'Dzięki, {name} — mamy termin',
        }),
        ec('headingColor', 'Kolor — nagłówek', '#ffffff'),
        defineField({
          name: 'subheadingTemplate',
          title: 'Podtytuł',
          description: '{slotMinutes} — długość slotu w minutach.',
          type: 'string',
          initialValue: 'Potwierdzenie rezerwacji {slotMinutes}-min rozmowy z Kamilem.',
        }),
        ec('subheadingColor', 'Kolor — podtytuł', '#aaaaaa'),
        defineField({
          name: 'meetLinkIntro',
          title: 'Tekst przed linkiem Meet (gdy kalendarz zwróci link)',
          type: 'text',
          rows: 2,
          initialValue: 'Link do Google Meet (otrzymasz też zaproszenie w kalendarzu):',
        }),
        ec('meetIntroColor', 'Kolor — tekst przed linkiem Meet', '#cccccc'),
        ec('meetLinkColor', 'Kolor — URL Google Meet', '#a78bfa'),
        defineField({
          name: 'fallbackNoMeetParagraph',
          title: 'Akapit gdy brak linku Meet (tylko .ics)',
          type: 'text',
          rows: 2,
          initialValue:
            'W załączniku znajdziesz plik .ics — kliknij, żeby dodać spotkanie do kalendarza.',
        }),
        ec('fallbackParagraphColor', 'Kolor — akapit z .ics', '#cccccc'),
        defineField({
          name: 'rescheduleNote',
          title: 'Informacja o przesunięciu / anulowaniu',
          type: 'text',
          rows: 2,
          initialValue: 'Chcesz przesunąć / odwołać? Wystarczy odpowiedzieć na tego maila.',
        }),
        ec('rescheduleNoteColor', 'Kolor — nota o przesunięciu', '#cccccc'),
        ec('mainContentTextColor', 'Kolor — treść bloku z datą i godziną', '#cccccc'),
        ec('dateStrongColor', 'Kolor — pogrubiona data i godzina', '#ffffff'),
        defineField({
          name: 'footerLine',
          title: 'Stopka',
          type: 'string',
          initialValue: 'Syntance • kamil@syntance.com',
        }),
        ec('footerLineColor', 'Kolor — linia w pasku stopki', '#666666'),
        ec('footerStripBackgroundColor', 'Tło paska stopki w karcie', '#0d0d0d'),
      ],
    }),
    defineField({
      name: 'meetingBookingOwner',
      title: '📥 Zespół — nowa rezerwacja rozmowy (plaintext)',
      group: 'meeting',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          description: '{meetingDateLabel}, {meetingTime}, {name}',
          type: 'string',
          initialValue: 'Nowa rozmowa: {meetingDateLabel}, {meetingTime} — {name}',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'bodyTemplate',
          title: 'Treść',
          description:
            'Tokeny: {slotMinutes}, {meetingDateLabel}, {meetingTime}, {name}, {email}, {companyLine}, {topicLine}, {sourceLine}, {calendarLine}, {meetLine}, {sanityLine} — linie opcjonalne mogą być puste.',
          type: 'text',
          rows: 14,
          initialValue: `Nowa rezerwacja {slotMinutes}-min rozmowy

Data: {meetingDateLabel}
Godzina: {meetingTime} ({slotMinutes} min)

Imię: {name}
Email: {email}
{companyLine}{topicLine}{sourceLine}{calendarLine}{meetLine}{sanityLine}`,
        }),
      ],
    }),
    defineField({
      name: 'contracts',
      title: '📄 Email z umowami',
      group: 'pipeline',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          description: tokenHelp,
          type: 'string',
          initialValue: 'Syntance - Umowy do zlecenia {bookingId}',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'headerEmoji',
          title: '😀 Emotka nad tytułem',
          description: headerEmojiHelp,
          type: 'string',
          initialValue: '📄',
          validation: (Rule) => Rule.max(32),
        }),
        ec('mailBackgroundColor', 'Tło karty maila', '#111111'),
        ec('sectionPanelBackgroundColor', 'Tło bloku podsumowania', '#1a1a1a'),
        defineField({
          name: 'heading',
          title: 'Nagłówek (h1)',
          type: 'string',
          initialValue: 'Umowy do Twojego zlecenia',
          validation: (Rule) => Rule.required(),
        }),
        ec('headingColor', 'Kolor — nagłówek h1', '#ffffff'),
        defineField({
          name: 'greetingTemplate',
          title: 'Powitanie',
          description: 'Użyj {name}. Domyślnie: „Cześć {name},”.',
          type: 'string',
          initialValue: 'Cześć {name},',
        }),
        ec('greetingColor', 'Kolor — powitanie', '#cccccc'),
        defineField({
          name: 'intro',
          title: 'Wstęp / treść główna',
          description: tokenHelp,
          type: 'text',
          rows: 5,
          initialValue:
            'W załączeniu przesyłamy umowy dotyczące realizacji Twojego zlecenia ({bookingId}).\n\nProsimy o zapoznanie się z dokumentami, podpisanie ich i odesłanie skanów na kontakt@syntance.com. Po otrzymaniu podpisanych umów wyślemy dane do płatności zaliczki.',
        }),
        ec('introColor', 'Kolor — wstęp', '#cccccc'),
        defineField({
          name: 'footerNote',
          title: 'Stopka treści (opcjonalnie)',
          type: 'text',
          rows: 2,
          initialValue: 'Pytania? Napisz na kontakt@syntance.com.',
        }),
        ec('footerNoteColor', 'Kolor — stopka treści', '#888888'),
        ec('referenceLineMutedColor', 'Kolor — etykieta „Nr referencyjny:” (tekst przed numerem)', '#9e9e9e'),
        ec('referenceLineAccentColor', 'Kolor — numer referencyjny w nagłówku', '#a29bfe'),
        ec('summarySectionHeadingColor', 'Kolor — nagłówek sekcji podsumowania (h3)', '#ffffff'),
        ec('tableLabelColor', 'Kolor — etykiety tabeli', '#888888'),
        ec('tableValueColor', 'Kolor — wartości tabeli', '#ffffff'),
        ec('tableAccentColor', 'Kolor — akcenty (zaliczka itd.)', '#a78bfa'),
      ],
    }),
    defineField({
      name: 'payment',
      title: '💳 Email z danymi do przelewu',
      group: 'pipeline',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          description: tokenHelp,
          type: 'string',
          initialValue: 'Syntance - Dane do płatności - {bookingId}',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'headerEmoji',
          title: '😀 Emotka nad tytułem',
          description: headerEmojiHelp,
          type: 'string',
          initialValue: '🎉',
          validation: (Rule) => Rule.max(32),
        }),
        ec('mailBackgroundColor', 'Tło karty maila', '#111111'),
        ec('sectionPanelBackgroundColor', 'Tło bloku podsumowania zlecenia', '#1a1a1a'),
        ec('paymentDetailsPanelBackgroundColor', 'Tło bloku „dane do przelewu”', '#0d0d0d'),
        ec('paymentDetailsBorderColor', 'Obramowanie bloku danych do przelewu', '#333333'),
        defineField({
          name: 'heading',
          title: 'Nagłówek (h1)',
          type: 'string',
          initialValue: 'Zlecenie potwierdzone!',
          validation: (Rule) => Rule.required(),
        }),
        ec('headingColor', 'Kolor — nagłówek h1 (sukces)', '#22c55e'),
        defineField({
          name: 'greetingTemplate',
          title: 'Powitanie',
          description: 'Użyj {name}.',
          type: 'string',
          initialValue: 'Cześć {name},',
        }),
        ec('greetingColor', 'Kolor — powitanie', '#cccccc'),
        defineField({
          name: 'intro',
          title: 'Wstęp',
          description: tokenHelp,
          type: 'text',
          rows: 4,
          initialValue:
            'Dziękujemy za podpisanie umów! Poniżej znajdziesz dane do wpłaty zaliczki, po której rozpoczynamy realizację projektu.',
        }),
        ec('introColor', 'Kolor — wstęp', '#cccccc'),
        defineField({
          name: 'footerNote',
          title: 'Stopka treści (opcjonalnie)',
          type: 'text',
          rows: 2,
          initialValue:
            'Po zaksięgowaniu wpłaty skontaktujemy się w sprawie startu projektu. Pytania? kontakt@syntance.com.',
        }),
        ec('footerNoteColor', 'Kolor — stopka treści', '#888888'),
        ec('referenceLineMutedColor', 'Kolor — etykieta „Nr referencyjny:” (tekst przed numerem)', '#9e9e9e'),
        ec('referenceLineAccentColor', 'Kolor — numer referencyjny w nagłówku', '#a29bfe'),
        ec('summarySectionHeadingColor', 'Kolor — nagłówek podsumowania (h3)', '#ffffff'),
        ec('tableLabelColor', 'Kolor — etykiety tabeli podsumowania', '#888888'),
        ec('tableValueColor', 'Kolor — wartości tabeli', '#ffffff'),
        ec('tableAccentColor', 'Kolor — zaliczka w tabeli', '#a78bfa'),
        ec('paymentDetailsHeadingColor', 'Kolor — tytuł „Dane do przelewu”', '#ffffff'),
        ec('transferTitleColor', 'Kolor — tytuł przelewu', '#a78bfa'),
        ec('transferAmountColor', 'Kolor — kwota przelewu', '#22c55e'),
      ],
    }),
    defineField({
      name: 'projectKickoff',
      title: '🎊 Start realizacji (po zaksięgowaniu zaliczki)',
      description:
        'Wysyłany z webhooka Attio, gdy deal trafi na etap „Aktywny”, „Realizacja” lub „W realizacji” (tytuł musi być identyczny jak status w CRM).',
      group: 'pipeline',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          description: tokenHelp,
          type: 'string',
          initialValue: 'Syntance - Zaczynamy realizację — {bookingId}',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'headerEmoji',
          title: '😀 Emotka nad tytułem',
          description: headerEmojiHelp,
          type: 'string',
          initialValue: '🥳',
          validation: (Rule) => Rule.max(32),
        }),
        ec('mailBackgroundColor', 'Tło karty maila', '#111111'),
        defineField({
          name: 'heading',
          title: 'Nagłówek (h1)',
          type: 'string',
          initialValue: 'Zaliczka u nas — zaczynamy realizację!',
          validation: (Rule) => Rule.required(),
        }),
        ec('headingColor', 'Kolor — nagłówek h1 (sukces)', '#22c55e'),
        defineField({
          name: 'greetingTemplate',
          title: 'Powitanie',
          description: 'Użyj {name}.',
          type: 'string',
          initialValue: 'Cześć {name},',
        }),
        ec('greetingColor', 'Kolor — powitanie (akcent)', '#86efac'),
        defineField({
          name: 'intro',
          title: 'Treść główna',
          description: tokenHelp,
          type: 'text',
          rows: 5,
          initialValue:
            'Dziękujemy za wpłatę zaliczki — mamy ją zaksięgowaną i uruchamiamy Twój projekt.\n\nW kolejnych dniach skontaktujemy się w sprawie pierwszych kroków i harmonogramu. Pytania? kontakt@syntance.com.',
        }),
        ec('introColor', 'Kolor — treść główna', '#cccccc'),
        defineField({
          name: 'footerNote',
          title: 'Stopka treści (opcjonalnie)',
          type: 'text',
          rows: 2,
          initialValue: 'Do zobaczenia po drugiej stronie kodu — zespół Syntance',
        }),
        ec('footerNoteColor', 'Kolor — stopka treści', '#888888'),
        ec('referenceLineMutedColor', 'Kolor — etykieta „Nr referencyjny:” (tekst przed numerem)', '#9e9e9e'),
        ec('referenceLineAccentColor', 'Kolor — numer referencyjny w nagłówku', '#a29bfe'),
      ],
    }),
    defineField({
      name: 'projectComplete',
      title: '✨ Koniec realizacji (status Zakończony)',
      description:
        'Wysyłany z webhooka Attio, gdy deal trafi na etap „Zakończony” (tytuł musi być identyczny jak status w CRM).',
      group: 'pipeline',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          description: tokenHelp,
          type: 'string',
          initialValue: 'Syntance - Dziękujemy — projekt {bookingId} zakończony',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'headerEmoji',
          title: '😀 Emotka nad tytułem',
          description: headerEmojiHelp,
          type: 'string',
          initialValue: '✨',
          validation: (Rule) => Rule.max(32),
        }),
        ec('mailBackgroundColor', 'Tło karty maila', '#111111'),
        defineField({
          name: 'heading',
          title: 'Nagłówek (h1)',
          type: 'string',
          initialValue: 'Realizacja zamknięta',
          validation: (Rule) => Rule.required(),
        }),
        ec('headingColor', 'Kolor — nagłówek h1', '#a78bfa'),
        defineField({
          name: 'greetingTemplate',
          title: 'Powitanie',
          description: 'Użyj {name}.',
          type: 'string',
          initialValue: 'Cześć {name},',
        }),
        ec('greetingColor', 'Kolor — powitanie (akcent)', '#93c5fd'),
        defineField({
          name: 'intro',
          title: 'Treść główna',
          description: tokenHelp,
          type: 'text',
          rows: 5,
          initialValue:
            'Dziękujemy za współpracę — zakończyliśmy uzgodniony zakres prac dla Twojego zlecenia ({bookingId}).\n\nJeśli pojawią się pytania lub potrzeba wsparcia po wdrożeniu, napisz na kontakt@syntance.com.',
        }),
        ec('introColor', 'Kolor — treść główna', '#cccccc'),
        defineField({
          name: 'footerNote',
          title: 'Stopka treści (opcjonalnie)',
          type: 'text',
          rows: 2,
          initialValue: 'Do zobaczenia przy kolejnych projektach — zespół Syntance',
        }),
        ec('footerNoteColor', 'Kolor — stopka treści', '#888888'),
        ec('referenceLineMutedColor', 'Kolor — etykieta „Nr referencyjny:” (tekst przed numerem)', '#9e9e9e'),
        ec('referenceLineAccentColor', 'Kolor — numer referencyjny w nagłówku', '#a29bfe'),
      ],
    }),
    defineField({
      name: 'rejection',
      title: '❌ Email o odrzuceniu',
      group: 'pipeline',
      type: 'object',
      fields: [
        defineField({
          name: 'subjectTemplate',
          title: 'Temat',
          description: tokenHelp,
          type: 'string',
          initialValue: 'Syntance - Informacja o zleceniu',
          validation: (Rule) => Rule.required(),
        }),
        defineField({
          name: 'headerEmoji',
          title: '😀 Emotka nad tytułem',
          description: `${headerEmojiHelp} Domyślnie puste.`,
          type: 'string',
          initialValue: '',
          validation: (Rule) => Rule.max(32),
        }),
        ec('mailBackgroundColor', 'Tło karty maila', '#111111'),
        defineField({
          name: 'heading',
          title: 'Nagłówek (h1)',
          type: 'string',
          initialValue: 'Informacja o zapytaniu',
          validation: (Rule) => Rule.required(),
        }),
        ec('headingColor', 'Kolor — nagłówek h1', '#ffffff'),
        defineField({
          name: 'greetingTemplate',
          title: 'Powitanie',
          type: 'string',
          initialValue: 'Cześć {name},',
        }),
        ec('greetingColor', 'Kolor — powitanie', '#cccccc'),
        defineField({
          name: 'body',
          title: 'Treść główna',
          description: tokenHelp,
          type: 'text',
          rows: 5,
          initialValue:
            'Dziękujemy za zainteresowanie współpracą z Syntance. Niestety, w tym momencie nie możemy przyjąć Twojego zlecenia.',
        }),
        ec('bodyColor', 'Kolor — treść główna', '#cccccc'),
        defineField({
          name: 'body2',
          title: 'Druga linia (opcjonalnie)',
          type: 'text',
          rows: 3,
          initialValue: 'Skontaktujemy się z Tobą wkrótce, aby omówić możliwe alternatywy.',
        }),
        ec('body2Color', 'Kolor — drugi akapit', '#cccccc'),
        defineField({
          name: 'footerNote',
          title: 'Stopka treści (opcjonalnie)',
          type: 'text',
          rows: 2,
          initialValue: 'Pytania? kontakt@syntance.com · +48 537 110 170',
        }),
        ec('footerNoteColor', 'Kolor — stopka treści', '#888888'),
        ec('referenceLineMutedColor', 'Kolor — etykieta „Nr referencyjny:” (tekst przed numerem)', '#9e9e9e'),
        ec('referenceLineAccentColor', 'Kolor — numer referencyjny w nagłówku', '#a29bfe'),
      ],
    }),
  ],
  preview: {
    prepare() {
      return {
        title: '📧 Treści emaili',
        subtitle:
          'Konfigurator · Kontakt · Rozmowa · Umowa · Przelew · Start · Koniec · Odrzucenie',
      }
    },
  },
})
