import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'pricingItem',
  title: 'Element cennika',
  type: 'document',
  groups: [
    { name: 'basic', title: 'Podstawowe', default: true },
    { name: 'pricing', title: 'Ceny i czas' },
    { name: 'behavior', title: 'Zachowanie' },
    { name: 'notifications', title: '🔔 Notyfikacje' },
    { name: 'display', title: 'Wyświetlanie' },
  ],
  fields: [
    // === PODSTAWOWE ===
    defineField({
      name: 'id',
      title: 'ID (unikalne)',
      type: 'slug',
      group: 'basic',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'name',
      title: 'Nazwa',
      type: 'string',
      group: 'basic',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Opis',
      type: 'text',
      group: 'basic',
    }),
    defineField({
      name: 'category',
      title: 'Kategoria',
      type: 'reference',
      to: [{ type: 'pricingCategory' }],
      group: 'basic',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'projectTypes',
      title: 'Typy projektów',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'projectType' }] }],
      group: 'basic',
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'order',
      title: 'Kolejność w kategorii',
      type: 'number',
      group: 'basic',
      initialValue: 0,
    }),

    // === CENY I CZAS ===
    defineField({
      name: 'price',
      title: 'Cena (PLN netto)',
      type: 'number',
      group: 'pricing',
      validation: (Rule) => Rule.required().min(0),
    }),
    defineField({
      name: 'hours',
      title: 'Czas realizacji (h)',
      type: 'number',
      group: 'pricing',
      validation: (Rule) => Rule.required().min(0),
    }),
    defineField({
      name: 'complexityWeight',
      title: 'Waga złożoności',
      type: 'number',
      group: 'pricing',
      initialValue: 1,
      description: 'Waga wpływająca na poziom złożoności (1 = standard, 2-3 = wyższy dla CMS/CRM/integracji).',
      validation: (Rule) => Rule.min(0).max(10),
    }),
    defineField({
      name: 'rateType',
      title: 'Typ stawki',
      type: 'string',
      group: 'pricing',
      options: {
        list: [
          { title: 'Development (programowanie)', value: 'dev' },
          { title: 'Consulting (konsultacje)', value: 'consulting' },
        ],
        layout: 'radio',
      },
      initialValue: 'dev',
      description: 'Określa czy produkt używa stawki dev czy consulting do kalkulacji',
    }),
    defineField({
      name: 'percentageAdd',
      title: 'Procentowy dodatek (%)',
      type: 'number',
      group: 'pricing',
      description: 'Np. 20 dla i18n (+20% do całości). Jeśli ustawione, pole "Cena" jest ignorowane.',
    }),
    defineField({
      name: 'maxQuantity',
      title: 'Maksymalna ilość',
      type: 'number',
      group: 'pricing',
      description: 'Np. max 10 podstron. Zostaw puste dla 1.',
    }),

    // === ZACHOWANIE ===
    defineField({
      name: 'required',
      title: 'Obowiązkowy element?',
      type: 'boolean',
      group: 'behavior',
      initialValue: false,
      description: 'Czy element jest zawsze zawarty w cenie bazowej (nie można usunąć)',
    }),
    defineField({
      name: 'defaultSelected',
      title: 'Domyślnie zaznaczony?',
      type: 'boolean',
      group: 'behavior',
      initialValue: false,
      description: 'Element jest domyślnie zaznaczony, ale klient może go usunąć',
    }),
    defineField({
      name: 'includedInBase',
      title: 'Wliczony w cenę bazową (gratis)?',
      type: 'boolean',
      group: 'behavior',
      initialValue: false,
      description: 'Element jest za darmo gdy wybrany - wliczony w cenę bazową projektu',
    }),
    defineField({
      name: 'dependencies',
      title: 'Wymaga elementów (blokada)',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'pricingItem' }] }],
      group: 'behavior',
      description: 'Elementy, które muszą być wybrane PRZED tym elementem (ten będzie zablokowany dopóki tamte nie są wybrane)',
    }),
    defineField({
      name: 'bundledWith',
      title: 'Automatycznie dodaje (pakiet)',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'pricingItem' }] }],
      group: 'behavior',
      description: 'Elementy które AUTOMATYCZNIE dodadzą się gdy wybierzesz ten element. Usunięcie któregokolwiek z pakietu usunie też ten element.',
    }),

    // === NOTYFIKACJE ===
    defineField({
      name: 'notificationOnAdd',
      title: '🔔 Pokaż notyfikację przy DODANIU',
      type: 'boolean',
      group: 'notifications',
      initialValue: false,
      description: 'Gdy klient doda ten element, wyświetli się komunikat z prośbą o potwierdzenie',
    }),
    defineField({
      name: 'notificationAddTitle',
      title: 'Tytuł notyfikacji (dodanie)',
      type: 'string',
      group: 'notifications',
      description: 'Np. "⚠️ Uwaga - dodatkowe wymagania"',
      hidden: ({ parent }) => !parent?.notificationOnAdd,
    }),
    defineField({
      name: 'notificationAddText',
      title: 'Treść notyfikacji (dodanie)',
      type: 'text',
      group: 'notifications',
      rows: 4,
      description: 'Treść komunikatu wyświetlanego klientowi. Możesz użyć \\n dla nowej linii.',
      hidden: ({ parent }) => !parent?.notificationOnAdd,
    }),
    defineField({
      name: 'notificationAddConfirmText',
      title: 'Tekst przycisku akceptacji (dodanie)',
      type: 'string',
      group: 'notifications',
      description: 'Domyślnie: "Akceptuję"',
      hidden: ({ parent }) => !parent?.notificationOnAdd,
    }),
    defineField({
      name: 'notificationAddCancelText',
      title: 'Tekst przycisku anulowania (dodanie)',
      type: 'string',
      group: 'notifications',
      description: 'Domyślnie: "Anuluj"',
      hidden: ({ parent }) => !parent?.notificationOnAdd,
    }),
    defineField({
      name: 'notificationOnRemove',
      title: '🔔 Pokaż notyfikację przy USUNIĘCIU',
      type: 'boolean',
      group: 'notifications',
      initialValue: false,
      description: 'Gdy klient usunie ten element (który był domyślnie zaznaczony), wyświetli się komunikat',
    }),
    defineField({
      name: 'notificationRemoveTitle',
      title: 'Tytuł notyfikacji (usunięcie)',
      type: 'string',
      group: 'notifications',
      description: 'Np. "⚠️ Czy na pewno chcesz usunąć?"',
      hidden: ({ parent }) => !parent?.notificationOnRemove,
    }),
    defineField({
      name: 'notificationRemoveText',
      title: 'Treść notyfikacji (usunięcie)',
      type: 'text',
      group: 'notifications',
      rows: 4,
      description: 'Treść komunikatu wyświetlanego klientowi. Możesz użyć \\n dla nowej linii.',
      hidden: ({ parent }) => !parent?.notificationOnRemove,
    }),
    defineField({
      name: 'notificationRemoveConfirmText',
      title: 'Tekst przycisku akceptacji (usunięcie)',
      type: 'string',
      group: 'notifications',
      description: 'Domyślnie: "Akceptuję"',
      hidden: ({ parent }) => !parent?.notificationOnRemove,
    }),
    defineField({
      name: 'notificationRemoveCancelText',
      title: 'Tekst przycisku anulowania (usunięcie)',
      type: 'string',
      group: 'notifications',
      description: 'Domyślnie: "Anuluj"',
      hidden: ({ parent }) => !parent?.notificationOnRemove,
    }),

    // === WYŚWIETLANIE ===
    defineField({
      name: 'popular',
      title: 'Popularne',
      type: 'boolean',
      group: 'display',
      initialValue: false,
      description: 'Pokaż badge "Popularne"',
    }),
    defineField({
      name: 'new',
      title: 'Nowość',
      type: 'boolean',
      group: 'display',
      initialValue: false,
    }),
    defineField({
      name: 'disabled',
      title: 'Wyłączony (niedostępny)',
      type: 'boolean',
      group: 'display',
      initialValue: false,
      description: 'Element będzie widoczny ale zaciemniony i niemożliwy do wybrania',
    }),
    defineField({
      name: 'hidePrice',
      title: 'Ukryj cenę',
      type: 'boolean',
      group: 'display',
      initialValue: false,
      description: 'Cena nie będzie wyświetlana klientowi (puste miejsce zamiast ceny), ale będzie doliczana do sumy',
    }),
  ],
  preview: {
    select: {
      title: 'name',
      price: 'price',
      category: 'category.name',
    },
    prepare({ title, price, category }) {
      return {
        title,
        subtitle: `${price?.toLocaleString('pl-PL') || 0} PLN | ${category || 'Brak kategorii'}`,
      }
    },
  },
  orderings: [
    {
      title: 'Kategoria + Kolejność',
      name: 'categoryOrder',
      by: [
        { field: 'category.order', direction: 'asc' },
        { field: 'order', direction: 'asc' },
      ],
    },
    {
      title: 'Nazwa A-Z',
      name: 'nameAsc',
      by: [{ field: 'name', direction: 'asc' }],
    },
    {
      title: 'Nazwa Z-A',
      name: 'nameDesc',
      by: [{ field: 'name', direction: 'desc' }],
    },
    {
      title: 'Cena rosnąco',
      name: 'priceAsc',
      by: [{ field: 'price', direction: 'asc' }],
    },
    {
      title: 'Cena malejąco',
      name: 'priceDesc',
      by: [{ field: 'price', direction: 'desc' }],
    },
    {
      title: 'Czas realizacji',
      name: 'hoursAsc',
      by: [{ field: 'hours', direction: 'asc' }],
    },
    {
      title: 'Złożoność rosnąco',
      name: 'complexityAsc',
      by: [{ field: 'complexityWeight', direction: 'asc' }],
    },
    {
      title: 'Złożoność malejąco',
      name: 'complexityDesc',
      by: [{ field: 'complexityWeight', direction: 'desc' }],
    },
  ],
})
